site_name: "Djblackberry64 Curriculum"
site_url: "https://djblackberry64.github.io/djblackberry64-curriculum/"
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  alternate:
    - name: English
      link: /djblackberry64-curriculum/
      lang: en
    - name: Deutsch
      link: /djblackberry64-curriculum/de/
      lang: de
  social:
    - icon: fontawesome/solid/rss
      link: /djblackberry64-curriculum/feed_rss_created.xml
  generator: false

plugins:
  - rss:
      match_path: "^en/.*\\.md$"
      date_from_meta:
        fields:
          - updated
          - date
        default_time: "00:00"
  - search
  - awesome-pages
  - i18n:
      docs_structure: folder
      fallback_to_default: false
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Djblackberry64 Curriculum"
        - locale: de
          name: Deutsch
          build: true
          site_name: "Djblackberry64 Kurs"
          default: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  # - toc
extra_css:
  - overrides/assets/stylesheets/lesson_nav.css
extra_javascript:
  - resources/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
